language: node_js
dist: trusty
node_js:
- '6'
before_script:
- npm install
script:
- npm run test
- npm run build
after_success:
- npm run coverage
deploy:
  provider: npm
  email: sebastian.lzy@gmail.com
  api_key:
    secure: xn3TpFfOAob0jSbsaiapjYoWykOxqec2XQt0iqTypd098qtfBAizK613qxWEHPO39D/3auCkCi9a8UFIeM7NUpwG/iAE8S3mAV6toDQDLQf8xA64aQyP8+jExmlbKWssL3vjMoj73G01kFE4uFK2zKmhjfLIjF/QSrhWJwi6jUDoy2vH06iueyUWxphe/dXr8eLflYCCMMJuNvjENYkhnhvF7VIPuZNeJfHI60sLjOqTne0alTsrGroRb0CDglKSvMua2Y3CtulU9jM0eSchG0ctJyM0AKq7KSDCSYfFIGLJgFHdye7UMF7lRZhrJq6211SQhmi/7ZLhMtxL2GfwItd8nExYNcXR35T1SIrgsc0GKbeXvpDNxa+a7YYO/ox2a1gYBz8xgNwW6H6SLDKHrwh0fw3pKjXJwnwJmqS27jGKeRlVuCW7xea6HObVgC3ZRAD3YY6Qznvs8FT0HhZYbKZC9lOM8C9GiQxrgNSWvLlxHZKanSU+AQiu7A2baBozXOCyAatVPSC9W1ypSatXERvywWQFv4vpMnI3Pj8CfBFPP4Zq1gg24CRaUg/V8Cj+49aWmrHcYy+Rv9aE++IQNx+yZOGT4n3ZxPbFBAKPGrE6Lg71GPUHwCcGx3zpREVUwbTAcPwUZuuPjbxlJZ4Y6c0Noe9/h6QJItpgHu5eSrU=
  on:
    tags: true
    repo: sebastianlzy/superagent-debugger
