language: node_js
dist: trusty
node_js: '6'
before_script: npm install
script:
- npm run test
- npm run build
after_success: npm run coverage
deploy:
  provider: npm
  email: sebastian.lzy@gmail.com
  api_key:
    secure: mh3mytHAEuZ8CH1YzBn7VY87MUZzTKh+oTiT7HX5LlN/5uF/zOSbSx1WLb1phvnP5R807A5HGwJIy6UADVVIiZv7TiHeogHZ01g5qpO14FAHvQ6Mwl43EwvR85Fv8J4K9EcWBLWcv26zGlpi8gBz8zTEytCIaBYiqPjFM3bX7hZFRTAnGDvfxRhVpwadUF3RhLe7DrXoWKln8Sz0OPXbh8jXiU0bz7ZIHAx8qgfJyMHv3qSHA4dUat5z2w8Ugrka0LuCKObJLyXdH4GhZd52F9Cpfw36GJxOiwEviiKtDyM/H8I0JufBXA1sYh1aFqaTMhQOm0dX7C+GKCKBuqMjPWO3KMC/PgiXQxNiuLiywTNXHBDuoP8qYcJ+Y4pez2+WVPqTgK+TlBiDjm/hmRBSKrnnIBgj4MyWV1j48MtnlUyvt7dOWgebliJ+rJRa2Luq5NIIW499rloF5nLfmJzmClS0rzZqbQrLfaLpWEUyAVVbB+AhWUU/ksieJtl2GjzWYd13CpqMKKYyAcbrxEJprtnfeqzSntjmFip5VICBBzE8cJ9gFFdq6z/QMagbs1IrrYwBRNzobgJOFySrJTqQ5SCFi+jW7aFxMV63rIWMmIFcUZ5cnly2HhAkd4EMZ2ecAN/EttLtQZXS6rj0sljm9bHpXEf+J0XEnPsSbIDCb0E=
  on:
    tags: true
    repo: sebastianlzy/superagent-debugger
